### ISSUE TITLE
UI does not show up, container terminates

### ISSUE THREAD

**Issue by chbndrhnns** [jlesage/docker-czkawka#12] opened 2022-11-28 20:28 UTC
Hi, 

Starting with version v22.11.1, I see a strange behaviour that I am unable to debug further. When I access the app in the browser, it crashes. The logs just contain these lines and setting the `CONTAINER_DEBUG` variable to see more details does not create more verbose output.

Any idea what I could try?

Bye,
Jo

```
czkawka_1  | [app         ] Gdk-Message: 20:24:22.270: Failed to get file transfer portal: Could not connect: No such file or directory
czkawka_1  | [supervisor  ] service 'app' exited (with status 1).
czkawka_1  | [supervisor  ] waiting termination of logger thread of service 'app'...
czkawka_1  | [supervisor  ] logger thread of service 'app' successfully terminated.
czkawka_1  | [supervisor  ] restarting service 'app'.
czkawka_1  | [supervisor  ] starting service 'app'...
czkawka_1  | [supervisor  ] started service 'app'.
czkawka_1  | [supervisor  ] service 'app' exited (with status 1).
czkawka_1  | [supervisor  ] waiting termination of logger thread of service 'app'...
czkawka_1  | [supervisor  ] logger thread of service 'app' successfully terminated.
czkawka_1  | [supervisor  ] restarting service 'app'.
czkawka_1  | [supervisor  ] starting service 'app'...
czkawka_1  | [supervisor  ] started service 'app'.
czkawka_1  | [app         ] Gdk-Message: 20:24:29.373: Failed to get file transfer portal: Could not connect: No such file or directory
czkawka_1  | [supervisor  ] service 'app' exited (with status 1).
czkawka_1  | [supervisor  ] waiting termination of logger thread of service 'app'...
czkawka_1  | [supervisor  ] logger thread of service 'app' successfully terminated.
czkawka_1  | [supervisor  ] restarting service 'app'.
czkawka_1  | [supervisor  ] starting service 'app'...
czkawka_1  | [supervisor  ] started service 'app'.
czkawka_1  | [app         ] Gdk-Message: 20:24:31.275: Failed to get file transfer portal: Could not connect: No such file or directory
```

**Comment by jlesage** [comment] 2022-11-29 00:48
How did you created the container (your `docker run` command) ?

**Comment by chbndrhnns** [comment] 2022-11-29 20:53
I am using this docker-compose file:

```yaml
version: '3.1'

services:
  czkawka:
    restart: unless-stopped
    image: jlesage/czkawka:v22.11.1
    environment:
      USER_ID: 1027
      GROUP_ID: 101
      SUP_GROUP_IDS: 100,105733
      CONTAINER_DEBUG: 1
    volumes:
      - ./data/config:/config:rw
      - /volume1/photo/isa+jo:/storage/volume1/photo/isa+jo:rw
      - /volume1/photo/MobileBackup:/storage/volume1/photo/MobileBackup:rw
      - /volume1/photo/zz-testing:/storage/volume1/photo/zz-testing:rw
      - /volume1/database:/storage/volume1/database:rw
      - /volume1/homes/isa:/storage/volume1/homes/isa:rw
      - /volume1/homes/jo:/storage/volume1/homes/jo:rw
    ports:
      - "5800:5800"

```

**Comment by jlesage** [comment] 2022-11-30 12:31
Can you do a quick test and try to not map `/config` to see if the problem is caused by something in the config ?

**Comment by chbndrhnns** [comment] 2022-12-12 07:37
It seems 2022.12.2 solved the issue for. I looked through the changes but could not figure out how exactly you fixed it? I only saw a change to the base image.

**Comment by jlesage** [comment] 2022-12-12 13:14
Correct, Czkawka didn't change in the latest version.

The latest version fixes an issue for people using the Synology UI to setup the container, which I think it's not your case.

**Comment by chbndrhnns** [comment] 2022-12-12 13:40
Ah, right, I just read "synology" which also applies to me but I am not using the UI. So it's even more interesting that I was able to run the tool now.

**Comment by jlesage** [comment] 2024-10-17 02:12
Closing this issue. Please re-open if needed.

**Closed by jlesage** 2024-10-17 02:12 UTC
